### PR TITLE
Snack bar message system

### PR DESCRIPTION
**Pull request by Johngtka**
Added snackbar as a user feedback, showing an error message as an example

ezgif com-video-to-gif(3)

### CODE REVIEW

**Comment by Johngtka** [comment]
How it is supposed to work (transmission map)

**Comment by Johngtka** [comment]
how the error display works

**Comment by Johngtka** [comment]
Squash and Merge proposal commit:
Snack bar message system (#10)
ezgif com-video-to-gif(3)

**Comment by macrog** [comment]
> Squash and Merge proposal commit: 
Snack bar message system (#10)

missing scope (feat)!! and the message is not really clear, remember not WHAT have you done but WHY? 
WHAT -> snackbar
WHY -> show feedback to a user 
```
feat: Show user feedback in a toast message (#10)

- 3 different toast background available, red - error, blue - info, green - success
```

when you gonna be doing squash and merge put things in this order please
image

**Review by macrog — APPROVED** [review]

**Pull request merged**
