### PR TITLE
Responsive Side Bar 

### PR DESCRIPTION
**Pull request by Johngtka**
The side menu has been added:

obraz

### CODE REVIEW

**Comment by Johngtka** [comment]
I do not know why the autocomplete system does not display the data taken autocomplete under it

**Comment by Johngtka** [comment]
all that's left to do is fix the icons and the data display

**Comment by Johngtka** [comment]
to repair avatar in side bar menu

**Comment by Johngtka** [comment]
this is a completed target this update
obraz

**Comment by Johngtka** [comment]
Squash and Merge proposal commit:  Feat: Responsive Side Bar  (#8)

**Review by macrog — APPROVED** [review]
🥇

**Pull request merged**
